Add ModalContext, add useEffect in FilterMenu and TextModal to close …
wm-pxel/langchain-testbench pull request #39
Opened 2023-07-12 03:52 UTC by winston-edwin-chiong

Created a `ModalContext.tsx` to track the current and last opened modal. Using the strings `"FilterMenu"` and `"TextModal"` to as modal ID's. Clicking on each modal sets context modal ID to either of the two strings and each modal checks whether value in context is equal to its own ID. Closes modal if ID unequal.

2023-07-12 17:53 UTC, acruikshank-wm requested changes
This is on the right track, but it has some issues. It will not close modals of the same type. It also appears to be missing changes to `QuickMenu`.

Also let's avoid piecemeal re-linting code without discussing first as a team.

2023-07-12 17:53 UTC, acruikshank-wm commented on app/src/components/FilterMenu.tsx
> +    <div className={`filter-menu ${modalOpen ? "open" : ""}`}>
BLOCKING: This is using non-project-standard linting rules. Almost none of the changes in this file should be happening. Please revert all these changes.

2023-07-12 17:53 UTC, acruikshank-wm commented on app/src/components/FilterMenu.tsx
> +    if (activeModalId !== "FilterMenu") {
BLOCKING: This condition is insufficient. This will close the FilterMenu if a different type of menu opens, but won't close it if another FilterMenu opens. There's currently only one FilterMenu, but this code should work if we add another. The activeModalId needs to be a unique key. This probably requires that we pass a 'key' parameter to the menu props.

2023-07-12 17:53 UTC, acruikshank-wm commented on app/src/components/FilterMenu.tsx
> +    // Global modal ID changed, check if global modal ID not is equal to local modal ID
These comments are self evident in the code. Leaving them here adds to the overall maintenance cost of the project. You should remove them.

2023-07-12 17:53 UTC, acruikshank-wm commented on app/src/components/FilterMenu.tsx
> +          setActiveModalId("FilterMenu")
BLOCKING: 
1. This should be the unique key that is discussed above.
2. We should only set the ID when opening the modal.

I would move this logic into a clickHandler function above. We shouldn't define too much logic in an attribute.

2023-07-12 17:53 UTC, acruikshank-wm commented on app/src/components/TextModal.tsx
> +    if (activeModalId !== "TextModal") {
BLOCKING: Same issue as in FilterMenu

2023-07-12 17:53 UTC, acruikshank-wm commented on app/src/components/TextModal.tsx
> +    <div className={`text-modal ${modalOpen ? "open" : ""}`}>
BLOCKING: Please undo the linting.

2023-07-12 17:53 UTC, acruikshank-wm commented on app/src/components/TextModal.tsx
> +            setActiveModalId("TextModal");
BLOCKING: See FilterMenu

2023-07-13 21:40 UTC, winston-edwin-chiong commented on app/src/components/FilterMenu.tsx
> +    <div className={`filter-menu ${modalOpen ? "open" : ""}`}>
Reverted linting.

2023-07-13 21:40 UTC, winston-edwin-chiong commented on app/src/components/FilterMenu.tsx
> +    // Global modal ID changed, check if global modal ID not is equal to local modal ID
Removed comments.

2023-07-13 21:41 UTC, winston-edwin-chiong commented on app/src/components/FilterMenu.tsx
> +    if (activeModalId !== "FilterMenu") {
Added modalKey to menu props.

2023-07-13 21:41 UTC, winston-edwin-chiong commented on app/src/components/FilterMenu.tsx
> +          setActiveModalId("FilterMenu")
Moved logic to own handler function; will only set ID when opening modal.

2023-07-13 21:41 UTC, winston-edwin-chiong commented on app/src/components/TextModal.tsx
> +    <div className={`text-modal ${modalOpen ? "open" : ""}`}>
Reverted linting.

2023-07-13 21:41 UTC, winston-edwin-chiong commented on app/src/components/TextModal.tsx
> +    if (activeModalId !== "TextModal") {
Resolved.

2023-07-13 21:41 UTC, winston-edwin-chiong commented on app/src/components/TextModal.tsx
> +            setActiveModalId("TextModal");
Resolved.

2023-07-14 17:39 UTC, winston-edwin-chiong commented
Reverted linting. Added changes to QuickMenu. Using chain ID as unique key.

2023-07-24 18:07 UTC, acruikshank-wm approved these changes
This looks great! I've made some small suggestions, but overall ready to merge.

2023-07-24 18:07 UTC, acruikshank-wm commented on app/src/components/Header.tsx
> +          <TextModal modalKey="new-menu-1" title="new" buttonText="Create" placeholder="name" enterValue={(name) => newChain(name)} validateInput={(text) => isNewChainNameValid(text)} />
NIT: It's unclear to me why this is `new-menu-1` instead of simply `new-menu`.  It's not a big deal, but I'd delete the -1 here and below if there's not a need for it.

2023-07-24 18:07 UTC, acruikshank-wm commented on app/src/components/FilterMenu.tsx
> +  }, [modalOpen, activeModalId]);
NIT: I don't think you need `modalOpen` as a dependency here.

2023-07-24 18:07 UTC, acruikshank-wm commented on app/src/components/QuickMenu.tsx
> +  }, [modalOpen, activeModalId]);
NIT: I don't think you need `modalOpen` as a dependency here.

2023-07-24 18:07 UTC, acruikshank-wm commented on app/src/components/QuickMenu.tsx
> +    if (!modalOpen) {
See comment about the potentially confusing order above.

2023-07-24 18:07 UTC, acruikshank-wm commented on app/src/components/TextModal.tsx
> +  }, [modalOpen, activeModalId]);
ibid

2023-07-24 18:07 UTC, acruikshank-wm commented on app/src/components/TextModal.tsx
> +    if (!modalOpen) {
ibid

2023-07-24 18:44 UTC, merged