Feature/import export chain
wm-pxel/langchain-testbench pull request #40
Opened 2023-07-24 14:52 UTC by pdavis68

Fixes #33

## Problem

There is no way to share langchains between databases/users. 

## Solution

1. Add JSON export and import functions for chains.
2. Export chain as a JSON object
3. Import JSON chain.

2023-07-24 19:51 UTC, acruikshank-wm requested changes
This is looking really good, but I would like some improvements.

1. We shouldn't be manipulating the DOM in a React app so we need to remove the `ReactDOM.createPortal` call.
2. The import and export logic serialization is way to complicated. All our database types are JSON serializable, so we should be leveraging that. We should be sending JSON to and from the server. And we should simplify the import save logic.
3. There's some cleanup. Like the debug console.logs and the extraneous package-lock.json.

2023-07-24 19:51 UTC, acruikshank-wm commented on lib/chain_service.py
> +    return json.dumps(
Chain service shouldn't be outputting a JSON string. Serialization should happen at the transport layer (server or CLI).

2023-07-24 19:51 UTC, acruikshank-wm commented on lib/chain_service.py
> +class CustomJSONEncoder(json.JSONEncoder):
This looks challenging to maintain. We don't need this to encode a single revision, so I don't understand why we need it to encode and export multiple revisions.

2023-07-24 19:51 UTC, acruikshank-wm commented on lib/chain_service.py
> +        if ancestor_revision:
This condition being false would indicate the database is corrupt. The condition is arguably unnecessary, but at very least it shouldn't be allowed to succeed with a missing revision.

2023-07-24 19:51 UTC, acruikshank-wm commented on lib/chain_service.py
> +    chain_revisions = [chain_revision]
This through 191 could be a list comprehension.

2023-07-24 19:51 UTC, acruikshank-wm commented on lib/chain_service.py
> +    for revision in data["revisions"]:
We export revisions from newest to oldest. We should assume that. That makes the following a lot simpler. We simply need to reverse the list, save each setting the parent to the new _id of the last and then setting the chain to reference the _id of the last chain saved.

2023-07-24 19:51 UTC, acruikshank-wm commented on lib/model/chain_revision.py
> +    extra = "allow"
This is frowned upon in Python. Why are we doing it?

2023-07-24 19:51 UTC, acruikshank-wm commented on server/testbench.py
> +        filename = f"{chain_name}_exported_chain.json"
This is weird. Why don't we just send it as JSON? It's easy enough to convert that to a blob on the the other end.

2023-07-24 19:51 UTC, acruikshank-wm commented on server/testbench.py
> +    if 'file' not in request.files:
Again, we could just be receiving this in JSON which would greatly simplify this code.

2023-07-24 19:51 UTC, acruikshank-wm commented on package-lock.json
> +{
This looks like a mistake. There shouldn't be a package-lock.json file in the root directory.

2023-07-24 19:51 UTC, acruikshank-wm commented on app/src/components/Header.tsx
> +    console.log('Import button clicked');
remove.

2023-07-24 19:51 UTC, acruikshank-wm commented on app/src/components/ImportChain.tsx
> +  console.log('Rendering ImportChain'); // Add this line
remove

2023-07-24 19:51 UTC, acruikshank-wm commented on app/src/components/Header.tsx
> +      const blob = await exportChain(chainName);
NIT: It would be nice if this was extracted somewhere. It's pretty generic and Header.tsx is getting a little crowded.

2023-07-31 19:20 UTC, pdavis68 commented on app/index.html
> +    <div id="chain-import-modal"></div>
Fixed

2023-07-31 19:20 UTC, pdavis68 commented on app/src/components/ImportChain.tsx
> +    const fileInput = document.getElementById('file_upload');
Fixed

2023-07-31 19:21 UTC, pdavis68 commented on lib/chain_service.py
> +    return json.dumps(
Fixed

2023-07-31 19:21 UTC, pdavis68 commented on server/testbench.py
> +    if 'file' not in request.files:
Fixed

2023-07-31 19:21 UTC, pdavis68 commented on package-lock.json
> +{
Fixed

2023-07-31 19:21 UTC, pdavis68 commented on app/src/components/ImportChain.tsx
> +  console.log('Rendering ImportChain'); // Add this line
Removed

2023-07-31 19:54 UTC, pdavis68 commented on app/src/components/Header.tsx
> +      const blob = await exportChain(chainName);
Fixed

2023-07-31 20:37 UTC, acruikshank-wm reviewed
There are still many questions and requests that have yet to be addressed.

2023-07-31 20:37 UTC, acruikshank-wm commented on app/src/components/Header.tsx
> +    var response = listChainsAndUpdateRevisions();
`listChainsAndUpdateRevisions` is an async function that returns a promise. Without this `await` the next line is nonsensical. Why is this changing?

2023-07-31 20:37 UTC, acruikshank-wm commented on server/testbench.py
> +    if 'file' not in request.files:
How is this fixed? It's stlll expecting a multipart request rather than a simple JSON payload.

2023-07-31 20:37 UTC, acruikshank-wm commented on lib/chain_service.py
> +    exported_chain = json.loads('[' + ','.join(revision.json() for revision in chain_revisions) + ']')
This function is still returning a string serialization instead of the Python objects. Serialization should happen outside the service.

2023-07-31 20:53 UTC, pdavis68 commented on lib/chain_service.py
> +def import_chain(chain_name, json_string):
Fixed

2023-07-31 21:01 UTC, pdavis68 commented on server/testbench.py
> +    if 'file' not in request.files:
Then again, I'm not understanding what you're asking for. Can you please be a little more detailed in what you need changed?

2023-07-31 21:02 UTC, pdavis68 commented on server/testbench.py
> +        filename = f"{chain_name}_exported_chain.json"
I'm not understanding what you're asking for here. Can you please give me more detail?

2023-07-31 21:14 UTC, acruikshank-wm commented on server/testbench.py
> +        filename = f"{chain_name}_exported_chain.json"
This line is unnecessary and was confusing me. This IS a simple JSON response so we don't need a Content Disposition header. I'm not sure if it's doing anything on the other, end, but, if so, it should be handled in the front end app.

2023-07-31 21:15 UTC, acruikshank-wm commented on server/testbench.py
> +                "Content-Disposition": f"attachment;filename={filename}"
This doesn't make any sense. There is no attachment. This isn't a multipart request.

2023-07-31 21:21 UTC, acruikshank-wm commented on server/testbench.py
> +    if 'file' not in request.files:
The import should not be sent as a file attachment in a multipart request. It should be sent as a list of revisions in JSON like all the other API methods. Once you're doing that, you can delete everything to line 104 (and the `else:` case below), and replace 104 with `revisions = parse_obj_as(List[ChainRevision], request.json)`.

2023-08-04 18:36 UTC, pdavis68 commented on server/testbench.py
> +    if 'file' not in request.files:
Think this is fixed now.

2023-08-04 18:36 UTC, pdavis68 commented on lib/chain_service.py
> +    chain = chain_repository.find_one_by({"name": chain_name})
Fixed

2023-08-04 18:43 UTC, pdavis68 commented on lib/chain_service.py
> +        if ancestor_revision:
Fixed, I believe. Please verify the new code is okay. ChatGPT wrote it for me.

2023-08-04 18:43 UTC, pdavis68 commented on lib/chain_service.py
> +    for revision in data["revisions"]:
Reversed the list

2023-08-04 18:43 UTC, pdavis68 commented on lib/model/chain_revision.py
> +    extra = "allow"
Removed. Doesn't seem to be causing issues, so not sure why I added it exactly.

2023-08-04 18:45 UTC, pdavis68 commented on server/testbench.py
> +        filename = f"{chain_name}_exported_chain.json"
Fixed

2023-08-04 18:48 UTC, pdavis68 commented on server/testbench.py
> +                "Content-Disposition": f"attachment;filename={filename}"
Dixed

2023-08-04 18:48 UTC, pdavis68 commented on lib/chain_service.py
> +    exported_chain = json.loads('[' + ','.join(revision.json() for revision in chain_revisions) + ']')
Fixed.

2023-08-04 18:49 UTC, pdavis68 commented on app/src/components/Header.tsx
> +    var response = listChainsAndUpdateRevisions();
Fixed

2023-08-07 14:35 UTC, acruikshank-wm approved these changes
This PR is better, but it still has some issues, but I'm approving it in the interest of moving forward. Please fix the things that won't take too much time before merging.

2023-08-07 14:35 UTC, acruikshank-wm commented on lib/chain_service.py
> +    exported_chain = json.loads('[' + ','.join(revision.json() for revision in chain_revisions) + ']')
If I'm reading this correctly, we're serializing all the pydantic models into JSON and then deserializing that JSON into dicts. Why not simply return chain revisions? We should be returning the pydantic models from the service.

2023-08-07 14:35 UTC, acruikshank-wm commented on lib/chain_service.py
> +def determine_llm_type(llm):
This appears to be unused. You should delete it.

2023-08-07 14:35 UTC, acruikshank-wm commented on lib/chain_service.py
> +    try:
This command should not succeed if the saves fail. You should remove all the exception handling from this function.

2023-08-07 14:35 UTC, acruikshank-wm commented on lib/model/chain_revision.py
> +
The original spacing (2 before a class, and none between the class declaration and the instance variables) was correct. Can you revert this?

2023-08-07 14:35 UTC, acruikshank-wm commented on server/testbench.py
> +    if exported_chain:
This should be a guard clause. ie.
``` python
exported_chain = chain_service.export_chain(chain_name)
if not exported_chain:
  return Response(...)

chain_json = ...
return Response(...)
```

2023-08-07 14:35 UTC, acruikshank-wm commented on server/testbench.py
> +    if 'file' not in request.files:
The serialization is better, but the import still being received as a file attachment to a multipart request.

2023-08-10 19:45 UTC, pdavis68 commented on server/testbench.py
> +    if 'file' not in request.files:
Okay, I think I have this figured out finally.

2023-08-10 19:45 UTC, pdavis68 commented on lib/chain_service.py
> +    if export_ids is None:
Fixed

2023-08-10 19:45 UTC, pdavis68 commented on lib/chain_service.py
> +def determine_llm_type(llm):
Yes, when we removed my over-complicated serialization it was obviated. Nice catch.

2023-08-10 19:46 UTC, pdavis68 commented on lib/chain_service.py
> +    try:
Removed.

2023-08-10 19:46 UTC, pdavis68 commented on lib/model/chain_revision.py
> +
If I understood this correctly, I believe this is good now.

2023-08-10 19:46 UTC, pdavis68 commented on server/testbench.py
> +    if exported_chain:
Of course. Fixed.

2023-08-10 22:48 UTC, pdavis68 commented
@acruikshank 

From lib/chain_service.py, you wrote:

"If I'm reading this correctly, we're serializing all the pydantic models into JSON and then deserializing that JSON into dicts. Why not simply return chain revisions? We should be returning the pydantic models from the service."

This is the one issue I did not fix. I took a couple shots at it and I just couldn't get it working and I don't want to hold this up anymore. I suspect it will be a trivial fix for you or anyone adept at Python.

2023-08-10 22:48 UTC, merged