Feature/vector search
wm-pxel/langchain-testbench pull request #42
Opened 2023-07-27 18:48 UTC by acruikshank-wm

## Problem

This PR introduces semantic (neural, vector) search to Testbench via a VectorSearchChain. Vector search allows the chain to retrieve text results from a database by their similarity to a provided query.

This feature relies on an external vector database that stores embeddings (currently Pinecone is the only supported database). It also requires access to an embedding model (which is somewhat different from a standard LLM model). This feature currently only supports OpenAI models and Huggingface models through the sentence-transformers package.

## Solution

This was already a pretty big PR, which I made worse by performing a few refactors. I'm adding comments to individual files to explain why they were changed or added and what sort of review is required.

1. Introduce VectorSearchChain as a new LangChain component chain that computes the embedding of a query and finds results from a vector database based on similarity to that embedding.
2. Add dependencies for pinecone and sentence-transformers that permits this chain to work.
3. Introduce VectorSearchSpec and designer UI to allow users to specify a vector search.
4. Refactor designer components so each component is in its own file.
5. Change styles to use sass and use style nesting to ensure styles are scoped to components.
6. Misc changes to ease python debugging

## Screenshots

<img width="1728" alt="Screen Shot 2023-07-27 at 1 09 14 PM" src="https://github.com/wm-pxel/langchain-testbench/assets/114444866/d8feb689-d0ab-4778-8892-4efbb840c2ed">

2023-07-27 18:52 UTC, acruikshank-wm commented on .vscode/launch.json
> +{
Added to ease python debugging.

2023-07-27 18:52 UTC, acruikshank-wm commented on .vscode/settings.json
> +{
Added to ease python debugging

2023-07-27 18:53 UTC, acruikshank-wm commented on app/src/components/Designer.tsx
This file had too much logic. I broke it out into individual designer components in the designers directory.

2023-07-27 18:55 UTC, acruikshank-wm commented on app/src/components/TextModal.tsx
> +    if (await validateInput(text)) {
This was a bug. validateInput was acting asynchronously, but had the wrong type.

2023-07-27 18:56 UTC, acruikshank-wm commented on app/src/components/designers/APISpecDesigner.tsx
> +import { useContext, useEffect, useCallback, useState } from "react";
This and all the Designer components other than VectorSearch are just a refactor to put this code in individual files. They require light review at most.

2023-07-27 18:56 UTC, acruikshank-wm commented on app/src/components/designers/DeleteChainButton.tsx
> +import QuickMenu from "../QuickMenu"
This is also just extracting code from the Designer component file.

2023-07-27 18:59 UTC, acruikshank-wm commented on app/src/components/designers/VectorSearchSpecDesigner.tsx
> +import { useContext, useEffect, useMemo, useState } from "react";
This is a new component and requires a more thorough review.

2023-07-27 19:03 UTC, acruikshank-wm commented on cli.py
> +  chain_service.initialize_services()
ensure we're initializing api keys.

2023-07-27 19:05 UTC, acruikshank-wm commented on requirements.txt
Upgraded LangChain and adding Pinecone, SentenceTransformers and their dependencies.

2023-07-27 19:06 UTC, acruikshank-wm commented on scripts/generate_openai_embeddings.py
This script helps set up a vector database with OpenAI embeddings.

2023-07-27 19:06 UTC, acruikshank-wm commented on scripts/generate_sentencetransformers_embeddings.py
This script helps set up a vector database with Huggingface embeddings.

2023-07-27 19:06 UTC, acruikshank-wm commented on scripts/run_vector_search_chain.py
This is some handy example code to test the VectorSearchChain.

2023-07-27 19:07 UTC, acruikshank-wm commented on scripts/send_to_pinecone.py
This is a utility to help populate a Pinecone database.

2023-07-27 21:04 UTC, pdavis68 requested changes
Minor, minor issues only.

2023-07-27 21:04 UTC, pdavis68 commented on app/src/components/designers/ParameterEditor.tsx
> +  )
Theoretically React's batched updates could cause this to mess up as updates from both onChange events could be batched together, if my understanding is correct.

I think it's pretty unlikely, though. You'd have to put something in both fields pretty quickly,

2023-07-27 21:52 UTC, acruikshank-wm commented on app/src/components/designers/ParameterEditor.tsx
> +  )
I see what you're saying. I split this into two functions so at least there won't be trouble between the closures and the event handlers. Beyond that, I don't think can come up with a better strategy that doesn't produce a render loop.

2023-07-28 18:23 UTC, okay-son approved these changes
I think this is a very cool feature! I think the PR can(?) be approved from my understanding and review.

2023-07-28 21:29 UTC, pdavis68 approved these changes
Looks good. There's still a lot of error checking that ought to happen as this gets built up. For example, the use of environment variables without checking to see if they exist or are valid.  There are tons of embedded strings that, if I were doing C#, I would make constants.

For example, look at all the hard coded strings here:

```
  def vector_store(self, query) -> VectorStore:    
    if self.database == 'pinecone':
      if 'index' not in self.database_params:
        raise ValueError('Missing index parameter for Pinecone database')

      # import just-in-time so auth will happen after env vars are loaded
      import pinecone
      from langchain.vectorstores.pinecone import Pinecone
      
      index = pinecone.Index(self.database_params['index'])
      return Pinecone(
        index,
        query,
        self.database_params.get('text_key') or 'text',
        namespace=self.database_params.get('namespace') or ''
      )
    else:
      raise ValueError(f'Unknown database: {self.database}')


  def _call(self, inputs: Dict[str, str]) -> Dict[str, str]:
    if self.embedding_engine == 'openai':
      self.embedding_params['openai_api_key'] = os.environ.get("OPENAI_API_KEY")
      embeddings = OpenAIEmbeddings(**self.embedding_params)
    elif self.embedding_engine == 'huggingface':
      model = self.embedding_params.get('model_name') or 'all-mpnet-base-v2'
      embeddings = HuggingFaceEmbeddings(**self.embedding_params, model_name=model)
    else:
      raise ValueError(f'Unknown embedding engine: {self.embedding_engine}')
```

But that stuff is more long-term changes. But thought I should mention it while it's on my mind.

2023-07-31 13:47 UTC, merged