Llm spec
wm-pxel/langchain-testbench pull request #45
Opened 2023-08-08 19:44 UTC by wmjrosenblatt

## Problem
Handles the issue that we were running into with langchain chatmodels where they couldn't be serialized and saved into the db. In order to prevent this issue or issues like it from happening in the future, we defined an LLMSpec which could be saved in the db and instead generate the LLM on the fly when a user wants to run a langchain

## Solution

modified all frontend/backend models and specs to: 
- rename chain specs to include chain in the name
- rename llm types to include llm in the name
- create an idea of an llm spec which allows for the abstraction, saving, and handling of different kinds of llms

modify the chain_service and chain_revisions to handle the moving over from LLMs to LLMSpecs
modify the lang_chain_context to handle LLMs instead of untyped objects

Additionally, I made a few opportunistic refactorings including:
- deleting/adding in extra/missing blank lines
- removing unused imports

2023-08-08 22:47 UTC, acruikshank-wm requested changes
This is looking pretty good. The only real problem is that LangChain already has OpenAI and HuggingFaceHub subclasses of LLM, so we shouldn't be writing our own. I have some suggestions for naming and other quibbles for which I'd appreciate some consideration.

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/chain_service.py
> +  filledLLMs = {}
This can be written:
``` python
filledLLMs = {key: llm.to_lang_llm() for key, llm in revision.llms.items()}
```

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/llms/huggingface_hub_llm.py
> +class HuggingFaceHubLLM(LLM):
BLOCKING: We should not be implementing our own LLM here. HuggingfaceLLMSpec should create a `langchain.llm.huggingface_hub.HuggingFaceHub` instance that implements `langchain.llm.LLM`. This should be deleted.

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/llms/openai_llm.py
> +class OpenAILLM(LLM):
BLOCKING: We should not be implementing our own BaseLLM here. HuggingfaceLLMSpec should create a `langchain.llm.openai.OpenAI` instance that implements `langchain.llm.LLM`. This should be deleted.

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/model/chain_revision.py
> +  llms: Dict[str, LLMSpec]
NIce!

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/model/lang_chain_context.py
> +  llms: Dict[str, LLM]
Thank you.

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/model/llm_spec.py
> +  llm_type: Literal["openai_llm"] = "openai_llm"
Once again, the "_llm" is redundant. This should just be "openai".

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/model/llm_spec.py
> +  def to_lang_llm(self) -> LLM:
This name doesn't make any sense. It should either be `to_lang_chain` (as in LangChain project), `to_lang_chain_llm`, or just `to_llm`. I like the first for consistency with the chain specs, but I like the last for brevity. You're call.

2023-08-08 22:47 UTC, acruikshank-wm commented on lib/model/tests/test_llm_spec.py
> +  if os.environ.get("OPENAI_API_KEY") is None:
Creating, serializing, and deserializing an LLMSpec should not trigger an OpenAI auth request. You should try removing this and see if the test still passes.

2023-08-09 00:07 UTC, wmjrosenblatt commented on app/src/components/EditLLMs.tsx
> +      llm_type: 'openai_llm',
Makes total sense

2023-08-09 00:08 UTC, wmjrosenblatt commented on lib/chain_service.py
> +  filledLLMs = {}
absolutely agree

2023-08-09 00:13 UTC, wmjrosenblatt commented on lib/model/llm_spec.py
> +  def to_lang_llm(self) -> LLM:
I like to_llm better

2023-08-09 00:16 UTC, wmjrosenblatt commented on lib/model/tests/test_llm_spec.py
> +  if os.environ.get("OPENAI_API_KEY") is None:
you're right, sorry about that

2023-08-09 18:04 UTC, acruikshank-wm approved these changes
Looks great! Thanks.

2023-08-09 18:06 UTC, merged