Simplify the chain context
wm-pxel/langchain-testbench pull request #58
Opened 2023-08-16 20:27 UTC by wmjrosenblatt

## Problem

The front end chain context is very complex right now and utilizes 3 versions of the chainspec to keep track of changes.

## Solution
Slightly change how the context manages the state to reduce it down to 2 versions of the chainspec

2023-08-16 20:28 UTC, wmjrosenblatt commented
Seems to work but please someone else verify locally that everything is working okay.

2023-08-18 14:39 UTC, acruikshank-wm requested changes
I don't think you should be removing the useCallbacks. That change does not seem to specifically address the problem you are solving. In the future, please try to call out and justify these tangential changes in the PR notes.

2023-08-18 14:39 UTC, acruikshank-wm commented on app/src/contexts/ChainSpecContext.tsx
> +  const insertChainSpec = (type: string, chainId: number, index: number): void => {
BLOCKING: I don't think this is a good idea. The best case is that we end up regenerating this function and re-rendering other components too often. The worst case is we end up with a component left with a callback with a stale reference to the dirty chain or chain id. Is there a specific reason why you are removing these `useCallback`s?

2023-08-18 14:39 UTC, acruikshank-wm commented on app/src/contexts/ChainSpecContext.tsx
> +  const deleteChain = (chainId: number): void => {
see above.

2023-08-18 14:39 UTC, acruikshank-wm commented on app/src/contexts/ChainSpecContext.tsx
> +  const updateDirtyChainSpec = (spec: ChainSpec): void => {
see above

2023-08-23 16:33 UTC, closed without merging