Implementation of transform chain
wm-pxel/langchain-testbench pull request #7
Opened 2023-06-24 18:32 UTC by pdavis68

Implements the transform chain to provide more powerful logic options.

I suspect you'll want changes and I've surely missed something, but I wanted it in checked in while it was working (I had it working last night and then broke it and that cost me some hours). It seems to run properly and it saves to the DB properly.

2023-06-26 15:28 UTC, pdavis68 commented
Updated to fix the styling of Output Keys and sizing of the textarea for the code.

2023-06-27 22:03 UTC, acruikshank-wm requested changes
I think there was some miscommunication. LangChain already has a TransformerChain. We don't need to create our own version (but we do need the TransformSpec and the designer.

It would be ideal if we could rename all the 'Transform' names to 'Transformer' since that's what the LangChain Chain is called.

The rest looks good though.

2023-06-29 20:47 UTC, pdavis68 commented on app/src/components/Designer.tsx
> +    setTransformFunc(value);
Fixed

2023-06-29 20:48 UTC, pdavis68 commented on app/src/components/Designer.tsx
> +  const formatReducer = useMemo(() => new FormatReducer(
Fixed

2023-06-29 20:48 UTC, pdavis68 commented on app/src/components/Designer.tsx
> +          <HighlightedTextarea
Changed to a textarea

2023-06-29 20:48 UTC, pdavis68 commented on app/src/components/style/Designer.css
> +.form-element .var-name-input, .var-name-output, .form-element .text-input, .form-element textarea {
Remvoed

2023-06-29 20:50 UTC, pdavis68 commented on lib/chains/transform_chain.py
> +class TransformChain(Chain):
I misunderstood how this all worked. I used the ReformatChain as a model, but probably should have used the LLM as a model. I was wondering how langchain was executing the code. I figured I was missing some sort of python behind the scenes voodoo.

2023-06-29 20:50 UTC, pdavis68 commented on lib/model/chain_spec.py
> +    return TransformChain(transform_func=self.transform_func, input_variables=self.input_keys, output_variables=self.output_keys)
Used the Langchain TransformChain.

2023-06-29 21:02 UTC, acruikshank-wm approved these changes
Nice work.

I have one suggestion about the initializer for the transform spec.

2023-06-29 21:26 UTC, pdavis68 commented on app/src/model/spec_control.ts
> +        transform_func: "",
I like that. Done.

2023-06-29 21:27 UTC, merged